### ISSUE TITLE
How to "Reload the app to see the REPL prompt" ?

### ISSUE THREAD

**Issue by olivergg** [drapanjanas/re-natal#10]
In the README documentation, it is mentionned that 
```You have to reload your app, and should see the REPL coming up with the prompt.```

Does this mean to reload the entire application ? On a real Android device, the only way I've managed to have a REPL prompt was to go to "debug js" to launch a chrome instance on the computer, but I'm not sure it's the proper way to do it.

Thanks ;)

**Comment by artemyarulin** [comment]
I guess author means React Native reload functionality from the development menu. Like in [getting started](http://facebook.github.io/react-native/docs/getting-started.html)
```
Press the menu button (F2 by default, or ⌘-M in Genymotion) and select Reload JS to see your change!
```
As far as I remember simple shake gesture will work as well for the real device

**Comment by artemyarulin** [comment]
Yep, from this link http://facebook.github.io/react-native/docs/running-on-device-android.html#content
```
Open the Developer menu by shaking the device or running adb shell input keyevent 82 from the command line.
```

**Comment by olivergg** [comment]
Thanks, I guess the phrase "reload your app" was a bit confusing ;)
