### ISSUE TITLE
re-natal use-figwheel should ignore .DS_Store files in imageDirs

### ISSUE THREAD

**Issue by gnl** [drapanjanas/re-natal#103]
When working on files in the image folder Finder sometimes creates .DS_Store files and currently I am running a small script before `re-natal use-figwheel` to delete them and prevent the app from crashing on launch.

Would be nice if it just ignored them. This seems like it should be a quick fix, let me know if it's not - I'll fork and look into it.

**Comment by drapanjanas** [comment]
There is a filter in [code](https://github.com/drapanjanas/re-natal/blob/v0.3.7/re-natal.coffee#L217). Though predicate is a bit confusing, but seems to work. I did very basic test, so maybe did not hit the bug.

**Comment by gnl** [comment]
Sorry, my bad. I just recently migrated a project from re-natal 0.2.29 to the current version and must only have tested with the old version, which as I see from git didn't yet contain the fix. Everything works as it should, thanks, closing this.
