### ISSUE TITLE
Is there any way to change the directory structure

### ISSUE THREAD

**Issue by danceasarxx** [drapanjanas/re-natal#104]
I am developing an android application only(not cross-platform) so I do not need to separate platform specific code into different folders. I do not plan to ever support iOS. Most of the arrangement of namespaces have to do with this seperation(outside that specified by react-native). I also took a look at the coffee script file for re-natal and noticed the directory structure is hard-coded directly(you use variables to specify platforms). I know this might not seem important but I would like to get it out of the way regardless

**Comment by drapanjanas** [comment]
Well, I think when project is generated you can remove iOS build config from project.clj and so you can get rid of namespace in you sources. Re-natal commands will still generate index.ios.js but that will not be used.

**Comment by danceasarxx** [comment]
The problem is `re-natal use-figwheel`(Not exactly a problem). It complains about not finding `env/ios/main.cljs`. Also `re-natal upgrade` will recreate the directories. But it doesn't really matter anymore so I'll close this.
