### ISSUE TITLE
Command "re-natal init FutureApp" failed,  how should I debug?

### ISSUE THREAD

**Issue by zhaoyul** [drapanjanas/re-natal#108]
re-natal init FutureApp -i reagent6

Creating FutureApp
☕  Grab a coffee! Downloading deps might take a while...
Creating Leiningen project
Updating Leiningen project
Creating React Native skeleton.
Creating Re-Natal config
Compiling ClojureScript

Command failed: lein prod-build

**Comment by drapanjanas** [comment]
Looks like the last step of init (compiling cljs) failed. Try running `lein prod-build` manually from console and check the output.

**Comment by mozinator** [comment]
re-natal init is also broken for me
`
re-natal init FutureApp -i reagent6
Creating FutureApp
☕  Grab a coffee! Downloading deps might take a while...
Creating Leiningen project
Command failed: lein new future-app
`

**Comment by mozinator** [comment]
deleting the ~/.m2/repository folder fixed it for me... very strange

**Comment by luckypradana123** [comment]
I got this error also when trying to run `lein prod-build` manually

[ampersanda@xlr8 reNatal]$ lein prod-build
'prod-build' is not a task. See 'lein help'.

**Comment by drapanjanas** [comment]
@luckypradana123 to run lein you have to `cd` into directory which contains `project.clj`. From the output it looks like that you do it from some other dir.

**Comment by mununki** [comment]
It might not be a perfect resolution, but it fixes me.
I'm using a different version of OpenJDK against the version which react-native recommends. So I run this command to init a project and no error pops.

```sh
JAVA_HOME="/Applications/Android Studio.app/Contents/jre/jdk/Contents/Home" re-natal init FirstCljsrn -i reagent6
```
