### ISSUE TITLE
figwheel 0.5.10 - goog.require could not find: figwheel.connect.ios

### ISSUE THREAD

**Issue by gnl** [drapanjanas/re-natal#110]
Recently upgraded my project bumping a number of dependency versions - figwheel 0.5.10 is required to build with clojure-1.9.0-alpha15, which is a good idea when using spec considering the improvements in every new version.

![simulator screen shot apr 26 2017 12 35 22](https://cloud.githubusercontent.com/assets/1690961/25428078/58c97d3e-2a7d-11e7-94d7-fca2f04b83fa.png)

**Comment by drapanjanas** [comment]
You can hot-fix it in figwheel-bridge.js (check 999615e9)
It will be part of 0.4.0

**Comment by gnl** [comment]
Worked great, thanks!
