### ISSUE TITLE
Move local configuration out of .re-natal

### ISSUE THREAD

**Issue by cogwheel** [drapanjanas/re-natal#112]
The .re-natal file serves conflicting roles, both storing local, transient configuration (E.g. android.host when switching between device & simulator), and storing configuration that should be shared among developers (pretty much everything else).

There should be a separation between local configuration and project configuration to better support .gitignore

**Comment by drapanjanas** [comment]
Agree. Perhaps we could have a separate optional file (for example .re-natal.local) wich would override "global" config with local one. 
Commands which change transient configuration could write to *.local file by default. Current behavior (writing to global .re-natal file) would be possible by using additional option -g.

**Comment by jeaye** [comment]
This is causing a lot of headache on my team, since some of us are using devices and other are using emulators. The shared android.host makes committing most error-prone.

Any plans on taking actioni with regard to the config separation, @drapanjanas? Thanks for your consideration!

**Comment by drapanjanas** [comment]
Yes, I have this in mind among next things to look into. There is a small problem though that host is also updated in `env.ios.main` namespace figwheel config. First idea of solving it is to read the value from .re-natal config instead of having it in both places.
