### ISSUE TITLE
React packager fails on first build

### ISSUE THREAD

**Issue by paulbutcher** [drapanjanas/re-natal#116]
I'm very much a React Native n00b, so forgive me if I'm missing anything here. I'm running through the instructions at https://github.com/drapanjanas/re-natal#creating-a-new-project and I get a React packager error on running `react-native run-ios`:

```
React packager ready.

 ERROR  ENOENT: no such file or directory, lstat '/Users/paul/Personal/rota-app/ios/build/Build/Intermediates/React.build/Debug-iphonesimulator/React.build/Objects-normal/x86_64/RCTBridge.o-6b373b5c'
{"errno":-2,"code":"ENOENT","syscall":"lstat","path":"/Users/paul/Personal/rota-app/ios/build/Build/Intermediates/React.build/Debug-iphonesimulator/React.build/Objects-normal/x86_64/RCTBridge.o-6b373b5c"}
Error: ENOENT: no such file or directory, lstat '/Users/paul/Personal/rota-app/ios/build/Build/Intermediates/React.build/Debug-iphonesimulator/React.build/Objects-normal/x86_64/RCTBridge.o-6b373b5c'
Loading dependency graph...~
Process terminated. Press <enter> to close the window
```

This only happens the first time I run `react-native run-ios`. All subsequent invocations work fine.

I've confirmed that deleting the project and re-creating with `re-natal init RotaApp` results in this error the first time I run `react-native run-ios`.

Am I missing anything?

**Comment by carocad** [comment]
@paulbutcher pretty sure this is a react-native problem not a re-natal one https://github.com/facebook/react-native/issues/11293
