### ISSUE TITLE
Do I need the whole XCode or just the Command Line tools for iOS and re-natal?

### ISSUE THREAD

**Issue by theronic** [drapanjanas/re-natal#118]
I have limited disk space. Do I need to install the entire XCode to do iOS development with re-natal?

I found [this guide](https://www.moncefbelyamani.com/how-to-install-xcode-homebrew-git-rvm-ruby-on-mac/), which seems to save some space.

Thanks you for any guidance :)

**Comment by drapanjanas** [comment]
Never tried that, though I think it is more ReactNative topic than re-natal. When using certain native components you might need to open your project in XCode to set them up.
