### ISSUE TITLE
upgrade to reagent v0.7.0 breaks figwheel mode

### ISSUE THREAD

**Issue by carocad** [drapanjanas/re-natal#122]
Steps to reproduce:
1. install latest version of re-natal
2. run `re-natal init foo`
3. run `re-natal use-figwheel`
4. run `react-native start`
5. run `react-native run-android`
6. confirm that the default app works !!
7. now change the dependency `reagent` from `0.6.1` to `0.7.0` in `project.clj`
8. run steps 3 to 5 again
9. The app should start and say `waiting for figwheel to load files` and then break with message `React module should be required before createClass`

Extra information:
- the only visible use of createClass in figwheel bridge is here: https://github.com/drapanjanas/re-natal/blob/master/resources/figwheel-bridge.js#L38
- running `react-native log-android` gives some extra information:
```
Starting the logger (/home/carocad/Apps/Android/Sdk/platform-tools/adb logcat *:S ReactNative:V ReactNativeJS:V)...
--------- beginning of system
--------- beginning of main
I/ReactNativeJS(15396): Running application "foo" with appParams: {"rootTag":1}. __DEV__ === true, development-level warning are ON, performance optimizations are OFF
W/ReactNativeJS(15396): Warning: React.createClass is no longer supported. Use a plain JavaScript class instead. If you're not yet ready to migrate, create-react-class is available on npm as a drop-in replacement. (https://fb.me/migrating-from-react-create-class)
I/ReactNativeJS(15396): Loading Closure base.
I/ReactNativeJS(15396): Shimming require
I/ReactNativeJS(15396): Shimming goog functions.
I/ReactNativeJS(15396): ==== Shimming jsloader ====
E/ReactNativeJS(15396): { [Error: React module should be required before createClass] line: 18, column: 72 }
```
- looking at the logs it is possible to identify exactly where did figwheel-bridge broke: https://github.com/drapanjanas/re-natal/blob/master/resources/figwheel-bridge.js#L217. Just after shimming google functions but unable to execute `ImportJs` function.
- reagent CHANGELOG does mention `createClass` as a change for v0.7.0. Not sure how relevant this is for us: https://github.com/reagent-project/reagent/blob/master/CHANGELOG.md#070-2762017

Hope it helps :)

**Comment by pesterhazy** [comment]
Thanks for the repro steps

The following patch fixes it for me:

[0001-Fixes-for-reagent-0.7.0.patch.txt](https://github.com/drapanjanas/re-natal/files/1148409/0001-Fixes-for-reagent-0.7.0.patch.txt)

**Comment by pesterhazy** [comment]
Relevant: https://facebook.github.io/react/blog/2017/04/07/react-v15.5.0.html#migrating-from-react.createclass

**Comment by carocad** [comment]
I can confirm that the proposed changes solved the problem in my project as well :)

**Comment by carocad** [comment]
@pesterhazy changing the `React.createClass` to `createReactClass` as explained in your reference also works me (with all other changes included)

**Comment by drapanjanas** [comment]
Thanks! Worked like a charm! 👍

**Comment by pesterhazy** [comment]
:+1:
