### ISSUE TITLE
Upcoming changes in reagent 0.8.0

### ISSUE THREAD

**Issue by pesterhazy** [drapanjanas/re-natal#128]
Recent changes in the cljs compiler allow including js libraries as namespaces. This may end up cleaning up the code for cljsrn users quite a bit.

Reagent will probably use this functionality: https://github.com/reagent-project/reagent/pull/306

This may also require some changes to re-natal, however. Off the top of my head, empty cljsjs namespaces will not be required anymore. It's not clear to me how the changes in both Reagent and the Cljs compiler will interact with the RN packager. It may be necessary to set the `target` compiler option to `:node-js`.

It would be a good idea to try moving re-natal to the upcoming reagent 0.8.0 SNAPSHOT version.

**Comment by drapanjanas** [comment]
Got it working in branch reagent-0.8 using ClojureScript 1.9.908 and `:target :nodejs`
Noticed that figwheel got much slower though. Dont know yet what is causing that.

**Comment by jeaye** [comment]
Any update on this getting into master?

**Comment by drapanjanas** [comment]
Reagent 0.8 is still alpha, so might be a bit early. 
Anyways, can you check if that branch working fine for you? The hot reloading was slow for me, but perhaps it was something with my setup. 
I am not comfortable merging it at the moment.

**Comment by carocad** [comment]
@drapanjanas dropping this over here hoping that it might be helpful.

If you haven't changed the automatic J's require inference code, this would break once you start using js libraries inside the namespaces. This is because the inference was based on the `(js/require)` regular expression. 

I don't have a good solution for that yet, but mentioning it is better than letting it fail ;)

**Comment by drapanjanas** [comment]
@carocad thanks, I am aware of this. I also do not have any good solution to solve it at the moment. 
Since re-natal v 0.9.0 Reagent 0.8.1 is working fine, but it still uses `(js/require)`. So I think this issue can be closed, but we should track the automatic requires separately
