### ISSUE TITLE
use-component name inaccurate

### ISSUE THREAD

**Issue by pesterhazy** [drapanjanas/re-natal#131]
The `use-component` action doesn't have a good name - this can be confusing for beginners. It is needed for components, but that's not all. You need to use it to register _any NPM module_ or _javascript file_ you want to require. So it's true for moment-js as well as for (visual) components.

Perhaps `re-natal require` or `re-natal use-node-dependency` as an alias would help?

Also the docs should mention that you can (and need to!) `use-component` any string that you can require, e.g. `@remobile/react-native-toast/index.js`.

**Comment by drapanjanas** [comment]
Agreed, added shorter more clear aliases. There is auto-require feature in `use-figwheel` which can be enabled by `enable-auto-require` command.

**Comment by pesterhazy** [comment]
Great!
