### ISSUE TITLE
Template runs iOS and Android code on startup

### ISSUE THREAD

**Issue by jeaye** [drapanjanas/re-natal#133]
As defined by the `:source-paths` here: https://github.com/drapanjanas/re-natal/blob/master/resources/project.clj#L20 there is an issue where prod builds will run `env.android.prod` and `env.ios.prod` on startup. Similarly, dev builds will run `env.android.dev` and `env.ios.dev` on startup. This is because both Android and iOS sources are grouped under `env/dev` or `env/prod`.

Here's an example, as per the README:

```bash
┌─(✓)[jeaye@oryx]─[~/projects/tmp][18:02:39]
└──╼ re-natal init FutureApp
Creating FutureApp
☕  Grab a coffee! Downloading deps might take a while...
Creating Leiningen project
Updating Leiningen project
Creating React Native skeleton.
Creating Re-Natal config
Compiling ClojureScript

To get started with your new app, first cd into its directory:
cd future-app

Run iOS app:
react-native run-ios > /dev/null

To use figwheel type:
re-natal use-figwheel
lein figwheel ios

Reload the app in simulator (⌘ + R)

At the REPL prompt type this:
(in-ns 'future-app.ios.core)

Changes you make via the REPL or by changing your .cljs files should appear live.

Try this command as an example:
(dispatch [:set-greeting "Hello Native World!"])

✔ Done

┌─(✓)[jeaye@oryx]─[~/projects/tmp][18:03:56]
└──╼ cd future-app/

┌─(✓)[jeaye@oryx]─[~/projects/tmp/future-app][18:04:02]
└──╼ tree env/
env/
├── dev
│   ├── env
│   │   ├── android
│   │   │   └── main.cljs
│   │   └── ios
│   │       └── main.cljs
│   └── user.clj
└── prod
    └── env
        ├── android
        │   └── main.cljs
        └── ios
            └── main.cljs

8 directories, 5 files
```

**Comment by jeaye** [comment]
Unfortunately, after refactoring to work around this issue, I've run into a design problem deeper than just the template: `.re-natal` also assumes the sources are laid out this way.

Give an adapted structure like this (following typical Leiningen profile practices):
```bash
$ env/
├── android
│   ├── dev
│   │   └── env
│   │       └── android
│   │           └── main.cljs
│   └── prod
│       └── env
│           └── android
│               └── main.cljs
├── dev
│   └── user.clj
└── ios
    ├── dev
    │   └── env
    │       └── ios
    │           └── main.cljs
    └── prod
        └── env
            └── ios
                └── main.cljs

15 directories, 5 files
```

When I try to run my normal build cycle:

```bash
$ re-natal use-figwheel
Cleaning...
index.ios.js was regenerated
index.android.js was regenerated
Host in RCTWebSocketExecutor.m was updated
ENOENT: no such file or directory, open 'env/dev/env/ios/main.cljs'
```
So it looks like something more fundamental will need to change for this. How people are running non-trivial apps with custom initialization per-platform, or without double initializing each startup is still unclear. It seems to me that everyone is affected.

**Comment by drapanjanas** [comment]
True, unfortunately at the moment project structure is not very flexible. Some of of functions of re-natal needs to access env/dev env/prod files. Maybe it is possoble to refactor and introduce more fine-grained configuration for the paths in .re-natal. Have no good ideas at the moment.

**Comment by jeaye** [comment]
Forcing this layout is not the problem; it's a reasonable layout that separates platform-dependent code from the shared code under `src/`. The only issue is that *the layout is forced, but the code isn't actually separated.* Android is still going to run the iOS code at startup, and vice versa. That's a big issue, which is much more important than allowing the project layout to be flexible.

I'm hoping you'll address this, since it's the focus of this ticket. Me trying to rework the layout was just an attempted fix.

**Comment by carocad** [comment]
@jeaye not sure if I understand this correctly but did you prove that both iOS and Android apps are running on startup?

AFAIK they are both being compiled but only the selected target is run due to the use of `:main          "env.android.main"`. Everything else should be strip away by the compiler since it is not reachable from the `main` namespace.

**Comment by jeaye** [comment]
Yeah, I proved it by commenting out the iOS code that was running on startup and seeing my double initialization go away. The same should be possible by following the barest re-natal template, which I can do to further minimize the problem space.
