### ISSUE TITLE
figwheel does not connect to app

### ISSUE THREAD

**Issue by milanbella** [drapanjanas/re-natal#134]
This is my very first time trying re-natal, I followed all the steps in readme and ran:

> lein figwheel

An figwheel hangs forewer in:

  Switch REPL build focus:
          :cljs/quit                      ;; allows you to switch REPL to another build
    Docs: (doc function-name-here)
    Exit: Control+C or :cljs/quit
 Results: Stored in vars *1, *2, *3, *e holds last exception object
Prompt will show when Figwheel connects to your application

A am I doing something wrong?, did I miss something?,  should I try it on fresh linux installation?,  Any help, hints would we very welcome.

**Comment by Rovanion** [comment]
Try `lein figwheel ios|android` with either ios or android.
