### ISSUE TITLE
Failure when running re-natal init

### ISSUE THREAD

**Issue by Rovanion** [drapanjanas/re-natal#136]
On 64-bit Ubuntu 16.04 right after installing re-natal with `sudo npm install -g re-natal` and react-native-cli with `sudo npm install -g react-native-cli`:

```
$ re-natal init FutureApp
Creating FutureApp
☕  Grab a coffee! Downloading deps might take a while...
Creating Leiningen project
Updating Leiningen project
Creating React Native skeleton.
Command failed: node -e "require('react-native/local-cli/cli').init('.', 'FutureApp')"
```

No further information is provided.

**Comment by Rovanion** [comment]
The issue seems to have been resolved by installing a newer version of NodeJS as per https://askubuntu.com/a/953362/118176. The README should be updated to reflect that a newer version of node is needed, though I have no idea which version of nodejs that is the breakpoint between working and non-working init.

I started out on nodejs 4.2.6 and am now on 8.4.0.

**Comment by drapanjanas** [comment]
It works on my machine (Mac) with node v7.1.0, so I think it's safe to set that as minimum in README

**Comment by jdormit** [comment]
I am seeing the same error on OSX with node v9.6.1. Any other advice for debugging?

**Comment by Bost** [comment]
I have this problem on Ubuntu  18.10. Some details:
- `.npmrc` doesn't exist on my machine
- I installed all the required npm packages using `yarn`
- I compiled `watchman` from the source using `./configure --without-python  --without-pcre --enable-lenient before make`
 ```
$ npm --version
6.9.0
$ nodejs --version
v11.13.0
$ react-native --version
react-native-cli: 2.0.1
react-native: n/a - not inside a React Native project directory
$ watchman --version
4.9.0
$ lein version
Leiningen 2.9.1 on Java 11.0.1 OpenJDK 64-Bit Server VM
$ re-natal init FutureApp
Creating FutureApp
☕  Grab a coffee! Downloading deps might take a while...
Creating Leiningen project
Updating Leiningen project
Creating React Native skeleton.
Command failed: node -e "require('react-native/local-cli/cli').init('.', 'FutureApp')"
```
Does anyone have an idea what to do here? Thanks in advance.
