### ISSUE TITLE
Error on `re-natal use-figwheel` with image subfolders

### ISSUE THREAD

**Issue by gtebbutt** [drapanjanas/re-natal#149]
Small issue on 7.1 - when there are non-empty subfolders present in the `images` folder, running `re-natal use-figwheel` gives the error `Cannot read property 'join' of undefined`. 

Took a little bit of hunting to pin it down to the subfolders, but it seemed worth flagging. Project is otherwise excellent and has been a huge help!

**Comment by oskarsliukis** [comment]
@gtebbutt i'm facing the same issue. Does that mean i can't group images by subfolders?

**Comment by drapanjanas** [comment]
Thanks for the effort of pinning down the issue to the subfolders! I will look into it. As a workaround you can try enabling auto-require feature `re-natal enable-auto-require`. Though its experimental and should work of you if you use only static (js/require ) and not via some custom macro.
