### ISSUE TITLE
Figwheel port configuration

### ISSUE THREAD

**Issue by povloid** [drapanjanas/re-natal#151]
Please, can You add figwheel **port configuration** support  for `.re-natal.local -> https://github.com/drapanjanas/re-natal/blob/master/resources/config.cljs`?

I working with two different applications in one time and I need to separate repls and figwheel ports.

**Comment by drapanjanas** [comment]
Yes that is possible, I will do that.

**Comment by povloid** [comment]
Very very thank for Your work
