### ISSUE TITLE
unknown command use-android-device on Arch Linux

### ISSUE THREAD

**Issue by olivergg** [drapanjanas/re-natal#16]
I'm trying to use an android emulator with re-natal, but the command
``` re-natal use-android-device avd```

raised the following error in the console :
```unknown command use-android-device. See re-natal --help for valid commands```

Using re-natal 0.2.18 on Arch Linux.

Is this command supported on Linux ?

**Comment by drapanjanas** [comment]
This command was added in version 0.2.19. 
In version 0.2.18 same can be achieved by command `use-figwheel -H 10.0.2.2` for avd

**Comment by olivergg** [comment]
@drapanjanas  thanks ;)
