### ISSUE TITLE
Project will not build with JDK 9

### ISSUE THREAD

**Issue by Lokeh** [drapanjanas/re-natal#160]
I'm on a new macOS with the following installed:
- JDK 9
- Clojure 1.9.0
- Node v9.3.0
- NPM v5.6.0

**Behavior:**

```
$ npm install -g re-natal
$ re-natal init MobileDemo
Creating MobileDemo
☕  Grab a coffee! I will use yarn, but fetching deps still takes time...
Creating Leiningen project
Updating Leiningen project
Creating React Native skeleton.
Creating Re-Natal config
Compiling ClojureScript
Command failed: lein prod-build

$ cd mobile-demo
$ lein prod-build
Compiling ClojureScript...
Exception in thread "main" java.lang.ClassNotFoundException: javax.xml.bind.DatatypeConverter, compiling:(cljs/util.cljc:1:1)
...
```

**Problem:**

See https://github.com/bhauman/lein-figwheel/issues/612

`javax.xml.bind` has been renamed and deprecated in JDK 9.

**Solution:**

In `project.clj`, add this to the top-level configuration:

```edn
 :jvm-opts ["--add-modules" "java.xml.bind"]
```

And then it works:

```
$ lein prod-build
Compiling ClojureScript...
Compiling "index.ios.js" from ["src" "env/prod"]...
Successfully compiled "index.ios.js" in 19.61 seconds.
Compiling "index.android.js" from ["src" "env/prod"]...
Successfully compiled "index.android.js" in 12.345 seconds.```

**Comment by Lokeh** [comment]
It looks like figwheel added this as a conditional in their lein template: https://github.com/bhauman/figwheel-template/commit/627fa1d95d19682ebcc39627c2785eaa70482e22

We should probably do the same

**Comment by drapanjanas** [comment]
Thanks! I am thinking of adding following jvm-opts as a generic solution:
```edn
 :jvm-opts ["-XX:+IgnoreUnrecognizedVMOptions" "--add-modules java.xml.bind"]
```
Can you try if that works for you?
It should work for JDK7,8,9

**Comment by clinoge** [comment]
@drapanjanas kind of new to the whole Clojure/JVM business but can report that
adding those options does the trick for JDK 9 (ArchLinux). Thanks!

**Comment by drapanjanas** [comment]
@clinoge thanks! 👍

**Comment by vinurs** [comment]
@drapanjanas 
` :jvm-opts ["-XX:+IgnoreUnrecognizedVMOptions" "--add-modules java.xml.bind"]`
this does not work on macos with java 9.0.1, then i modify it to
`  :jvm-opts ["-XX:+IgnoreUnrecognizedVMOptions" "--add-modules" "java.xml.bind"]`
it works ok on my macos
