### ISSUE TITLE
Run iOS real device

### ISSUE THREAD

**Issue by nrakochy** [drapanjanas/re-natal#161]
I am running into the same issue as this [Stackoverflow question](https://stackoverflow.com/questions/46194474/re-natal%C2%B4s-react-native-run-ios-always-runs-on-simulator).

````
re-natal use-ios-device real 
re-natal use-figwheel
react-native run-ios
````
continues to launch the simulator instead of installing on my phone.

I also tried 

````
re-natal use-ios-device <ip.number>
````

but the result is the same.

How might I get this loaded up correctly on my phone? Thanks...

**Comment by MageMasher** [comment]
I actually start the app through xcode for the first time to make sure it loads on the device, then every time it starts on the device it points to figwheel correctly. 
I do have to execute the below statements though.
```
re-natal use-ios-device real 
re-natal use-figwheel
react-native run-ios
```

**Comment by nrakochy** [comment]
Thanks for the note.  I was looking at an issue on [Status.im](https://github.com/status-im/status-react) and hoping to avoid updating all of the bundle identifiers, but alas, will give it a whirl...

**Comment by nrakochy** [comment]
So I am not sure if this simulator is a default setting with `react-native run-ios`-


````
 react-native run-ios [options]
  builds your app and starts it on iOS simulator

  Options:

    --simulator [string]      Explicitly set simulator to use (default: iPhone 6)
    --configuration [string]  Explicitly set the scheme configuration to use
    --scheme [string]         Explicitly set Xcode scheme to use
    --project-path [string]   Path relative to project root where the Xcode project (.xcodeproj) lives. The default is 'ios'. (default: ios)
    --device [string]         Explicitly set device to use by name.  The value is not required if you have a single device connected.
    --udid [string]           Explicitly set device to use by udid
    --no-packager             Do not launch packager while building
    --verbose                 Do not use xcpretty even if installed
    --config [string]         Path to the CLI configuration file
    -h, --help                output usage information

  Example usage:

    Run on a different simulator, e.g. iPhone 5:
    react-native run-ios --simulator "iPhone 5"

    Pass a non-standard location of iOS directory:
    react-native run-ios --project-path "./app/ios"

    Run on a connected device, e.g. Max's iPhone:
    react-native run-ios --device "Max's iPhone"
````

Connecting to same wifi as phone, plugged in via USB, and running `react-native run-ios --udid "uniqueId" ` seems to be working for me now.
