### ISSUE TITLE
Unable to require local static images

### ISSUE THREAD

**Issue by jeaye** [drapanjanas/re-natal#162]
Hey there. I've been looking to bring in some local static images, so I've done the following:

* Create a `./images/logo.png` file at the root of the project
* Set `"imageDirs": ["images"],` in `.re-natal`
* Run `re-natal use-figwheel`
* Check that `index.android.js` contains `modules['./images/logo.png']=require('./images/logo.png');`
* Use the following ClojureScript `(def logo (js/require "./images/logo.png"))`

Alas, I only see `Error: Unknown named module: './images/logo.png']` on startup now. I've been through all the re-natal and React Native docs on the subject; what am I missing?

### Info
* re-natal version: 0.8.0
* React Native version: 0.50.4
* ClojureScript version: 1.9.946
* Platform: Android

**Comment by jeaye** [comment]
@carocad mentioned on Slack that reinstalling the app can help this and the situation arises commonly for him as well.

I uninstalled the app, then ran `react-native run-android` again and the error is now gone. If reinstalling is required each time a new image is added, along with running `re-natal use-figwheel`, I think we should document it.

**Comment by drapanjanas** [comment]
What is the operating system which runs metro bundler in your case? 
Did you try restarting the metro bundler? I suspect that bundler for some reason failed to dectect new image files and therefore statement `require('./images/logo.png')` in android.index.js could be failing.
I can create a wiki page  like "Trobleshooting" which would reference issues like this one.

**Comment by drapanjanas** [comment]
Thanks for confirming, I will check this also on my mac and will update the docs

**Comment by jeaye** [comment]
Excellent. Thank you!

**Comment by jeaye** [comment]
@drapanjanas Any luck confirming? Ideally we can mention this here: https://github.com/drapanjanas/re-natal#adding-an-image-during-development

**Comment by drapanjanas** [comment]
Unfortunately I could not reproduce this on my Mac with Android (via genymotion). I do not need to restart Metro bundler nor do I need to run `react-native run-android` to images to be resolved. So it might be some Linux thing.  
Yes, I can add there smth like ' On Linux you might need to run `react-native run-android`' with link to this issue.

**Comment by jeaye** [comment]
@drapanjanas Thanks so much for the update. Until we pinpoint whether it's specifically an issue only on GNU/Linux, it might be worth saying something like:

```markdown
If your images aren't able to be required after running `re-natal use-figwheel`,
you may need to also run `react-native run-android`.
```

**Comment by drapanjanas** [comment]
Agree, done. Let's see if someone else can confirm this issue.
