### ISSUE TITLE
Re-frisk and target node

### ISSUE THREAD

**Issue by nrakochy** [drapanjanas/re-natal#165]
Would you consider a PR for [re-frisk integration](https://github.com/flexsurfer/re-frisk/wiki/Using-re-frisk-with-re-natal)? 

How about [[:target :nodejs]](http://blog.fikesfarm.com/posts/2017-07-17-cleaner-clojurescript-react-native-interop.html) in the `project.clj`?

**Comment by piotr-yuxuan** [comment]
In my humble opinion that would be SUPER helpful! how would you do that? Do you think it would be compatible both on iOS and Android?

**Comment by drapanjanas** [comment]
@nrakochy Sure, I do think re-frisk is helpful! 
It would be good if users can optionally choose it when generating a new project.

Regarding `[:target :nodejs] I was experimenting with it in branch `reagent-0.8` but have not yet decided to go with that to master. Currently I have very limited time to contribute to re-natal so any help is welcome.

**Comment by nrakochy** [comment]
Got a bit distracted from `React Native` & `cljs`. Closing it out for now...
