### ISSUE TITLE
re-natal upgrade fails with "Cannot read property 'length' of undefined"

### ISSUE THREAD

**Issue by cldwalker** [drapanjanas/re-natal#17]
Hi. While taking a look at luno-react-native I had the above error.

Steps to reproduce:
1. git clone luno-react-native to https://github.com/alwx/luno-react-native/commit/122d541a4fc7de6e84a0c45ac2e263f5695f7580
2. re-natal upgrade

The failure seems to be coming from [editing a non-existing file](https://github.com/drapanjanas/re-natal/blob/eb969d8709d7c8ddeb446678b9759365a8c44896/re-natal.coffee#L253) on older projects. This can be fixed by putting a file exists check before that line is invoked. Since that fn is called by multiple contexts, we may need to pass a boolean to patchReactNativePackager to check whether the file exists or not. Happy to submit a PR if you explain the approach you want.

For this particular case it would've been helpful if there was a stacktrace. Setting [this event](https://nodejs.org/docs/latest/api/process.html#process_event_uncaughtexception) may help with that

Thanks for re-natal and look forward to using it more!

**Comment by drapanjanas** [comment]
Hi, 
The Problem might be that npm dependencies are not installed after cloning, please use `npm i`
Also, luno was updated yesterday, you might try pulling latest changes and trying that. Also readme of luno now better describes steps how to have it running. 

Thanks for proposal I like it. I think re-natal could benefit with the check that at least /node_modules folder not there, and similar checks. Stacktraces of unhandled errors also would be good. PRs are welcome.

**Comment by drapanjanas** [comment]
Should be fixed in v0.2.20

**Comment by cldwalker** [comment]
Thanks for the fix! :+1:
