### ISSUE TITLE
assembleRelease hangs on :app:bundleReleaseJsAndAssets in RN 0.53.3

### ISSUE THREAD

**Issue by jlo1** [drapanjanas/re-natal#170]
Upgraded my react-native version to 0.53.3. This caused the build to get stuck on the `bundleReleaseJsAndAssets` step when running `./gradlew assembleRelease`. Also had this issue on 0.50.3 as well. Steps to reproduce on fresh re-natal project:
```
> re-natal init FutureApp
> cd future-app
> react-native-git-upgrade
> lein prod-build && mv index.android.js index.js
> cd android && ./gradlew assembleRelease
```

Current workaround is to downgrade back down to RN 0.48.4, but would be nice to use latest RN version if possible

**Comment by drapanjanas** [comment]
From the command above I noticed that you keep the changes of version 0.49+ of single entry point `index.js` re-natal can not work with this setup at the moment. 
So you have to rollback these changes when you do `react-native-git-upgrade` as explained in [Release notes of react-native 0.49](https://github.com/facebook/react-native/releases/tag/v0.49.0)
>revert changes done by react-native-git-upgrade in order to keep separate entry files. That is, as soon as you upgrade, revert changes made to AppDelegate.m, MainApplication.java and build.gradle.

For react native 0.49+ you have to use re-natal 0.8+
Unfortunatly, I do not know what causes the hanging. That are internals of React Native and re-natal does not modify that as much as possible. As last resort you could generate new project make sure script does not hang there, and migrate your code...

**Comment by ubermenschjo** [comment]
my small hack is adding ignore block to .babelrc file. it is safe.
`{
    "presets": ["react-native"],
    "ignore": ["index.ios.js","index.android.js"]
}
`

**Comment by esutton** [comment]
This wasted hours and sadly I never learned the cause.

I deleted my source folder, then cloned a new one and all was good again.

**Comment by zabojad** [comment]
In my case, I couldn't find why it was happening  exactly. The symptom was an out of memory error but event increasing the heap size to 8gb did not solve it (it hung  3 hours on the app:bundleReleaseJsAndAssets task and crashed).

I was using node v8.11.3. I replaced it (nvm) with node v13.12.0 and the project compiled in no time.

If only I knew before wasting so many hours...
