### ISSUE TITLE
Document how to change Figwheel port

### ISSUE THREAD

**Issue by mfikes** [drapanjanas/re-natal#177]
If you end up with a port conflict with the default Figwheel port, I think it would be nice if there was a small section in the README that described how to do this.

I think the steps involve two things—but I'm not completely sure as I'm guessing without the documentation :)

1. Have the Figwheel server start on a different port
2. Run `re-natal set-figwheel-port` passing the desired port

Part (1) could also be expanded upon in the documentation: It appears that you can do this using `:figwheel {:server-port xxxx}` if starting things via `lein figwheel ios`, but if instead you are in a REPL and do `(start-figwheel "ios")`, this doesn't seem to be picked up.

**Comment by mfikes** [comment]
Thanks @drapanjanas !

**Comment by zendevil** [comment]
@mfikes didn't work for me. It's still trying 3449.
