### ISSUE TITLE
RN 0.56.0 support

### ISSUE THREAD

**Issue by jeaye** [drapanjanas/re-natal#189]
Hey @drapanjanas. :)

I've been working on trying to get re-natal up to speed with RN 0.56.0 after an overzealous upgrading session. To start with, I've identified one issue with a quick fix.

1. `error: bundling failed: Error: Unable to resolve module 'figwheel-bridge'`

    This is fixed by updating `index.android.js` to `require('./figwheel-bridge')` instead. So, we can just change https://github.com/drapanjanas/re-natal/blob/dac3e2044dfddc79b5dedfa26cd9817be4730f41/re-natal.coffee#L771 to do this.

Once that's out of the way, I start seeing `Uncaught TypeError: goog.nodeGlobalRequire is not a function` on startup. Interestingly, when searching for this issue, I see https://github.com/drapanjanas/re-natal/issues/128 come up, which is referenced by https://github.com/retro/graphql-builder/issues/4. Looks like others have had this issue, but worked around it by just not using the library which caused it. In general, that's likely not a dependable solution.

I've hit a bit of a wall now. What do you see as the way forward?

RN: `0.56.0`
re-natal: `0.9.0`
CLJS: `[org.clojure/clojurescript "1.10.238"] `
Reagent: `[reagent "0.8.1"] `
Target: `:nodejs`

**Comment by maridonkers** [comment]
Also here are two vulnerabilities reported when not upgraded to 0.56.0:

```
$ npm audit
                                                                                
                       === npm audit security report ===                        
                                                                                
# Run  npm install react-native@0.56.0  to resolve 2 vulnerabilities
┌───────────────┬──────────────────────────────────────────────────────────────┐
│ Low           │ Prototype Pollution                                          │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Package       │ lodash                                                       │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Dependency of │ react-native                                                 │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Path          │ react-native > plist > xmlbuilder > lodash                   │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ More info     │ https://nodesecurity.io/advisories/577                       │
└───────────────┴──────────────────────────────────────────────────────────────┘


┌───────────────┬──────────────────────────────────────────────────────────────┐
│ High          │ Denial of Service                                            │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Package       │ ws                                                           │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Dependency of │ react-native                                                 │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Path          │ react-native > react-devtools-core > ws                      │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ More info     │ https://nodesecurity.io/advisories/550                       │
└───────────────┴──────────────────────────────────────────────────────────────┘


found 2 vulnerabilities (1 low, 1 high) in 34468 scanned packages
  run `npm audit fix` to fix 2 of them.
```

(Tried to run `npm audit fix` but my project didn't work afterwards.)

**Comment by olivergeorge** [comment]
For what it's worth I just did a trial upgrade to RN 0.56.0 and things seemed to go well.  (Need more testing to confirm though.)

Steps were:
* Run `react-native-git-upgrade` & fix merge conflicts
* Patch index.ios.js to require figwheel bridge with a relative path (e.g. `require('./figwheel-bridge')...` 
* Update `babel-preset-react-native` to "5.0.2" (manually, surprised this wasn't done for me)
* Update a few other deps for compatibility with RN 0.56.0

**Comment by vikeri** [comment]
I had to change figwheel to load the import scripts async with Chrome to get fighweel to work. I.e. setting this to false: https://github.com/drapanjanas/re-natal/blob/a976a59d53ef5f58d86f7ead68d97466e977c22f/resources/figwheel-bridge.js#L147

**Comment by drapanjanas** [comment]
v0.11.1 works with latest React Native version
