### ISSUE TITLE
support Figwheel Main

### ISSUE THREAD

**Issue by vinurs** [drapanjanas/re-natal#204]
Hi,
   there seems that figwheel main will instead of lein figwheel, is there any plan to support it ?
![image](https://user-images.githubusercontent.com/37489300/49052916-e0448280-f228-11e8-8ba0-d3289abbd4c2.png)

https://figwheel.org/

**Comment by drapanjanas** [comment]
I will definitely have a look what would it take to have it working

**Comment by vinurs** [comment]
Now, there is no need to support figwheel main, shadow-cljs will be better
