### ISSUE TITLE
klaw-sync problem

### ISSUE THREAD

**Issue by neutrous** [drapanjanas/re-natal#205]
When uses `enable-auto-require`, current dependent `klaw-sync` wouldn't correctly handle recursively filter `cljs` files, which could cause generating index.*.js failure.

What we should do is as follows:

1. Change to klaw-sync@6.0.0
2. Provide `traverseAll: true` for options parameter

**Comment by philoskim** [comment]
I ran the following commands according to the advice and succeeded.

Thank you for this solution!

```
$ npm install klaw-sync -g

$ re-natal {traverseAll: true} require-all
```

**Comment by drapanjanas** [comment]
I guess, this works correctly now, closing
