### ISSUE TITLE
Command for copyFigwheelBridge

### ISSUE THREAD

**Issue by cldwalker** [drapanjanas/re-natal#22]
Hi. Would you take a PR for a command that just calls copyFigwheelBridge() with name from the config? We'd like to pull in the great upstream work you're doing on figwheel-bridge.js. doUpgrade() doesn't work for us because we have a different project layout than env/ and "src/#{projNameUs}/ios/core.cljs" and we're not looking to use the other changes e.g. patch react-native. Cheers

**Comment by drapanjanas** [comment]
Yes, makes sense, I see no problem having command like that.
It is also interesting to know what setup you have instead of /env. And what problems you experienced. Maybe you have some mprovements which also could be useful to others.

**Comment by drapanjanas** [comment]
Another thing to note, is that current figwheel-bridge is coupled with env/ setup [here](https://github.com/drapanjanas/re-natal/blob/master/resources/figwheel-bridge.js#L169) and [here](https://github.com/drapanjanas/re-natal/blob/master/resources/figwheel-bridge.js#L166)

**Comment by cldwalker** [comment]
I'll definitely let you know of improvements as we come across them. So far it's working great :). I'm aware of that env setup and am able to use it as is fine. We have src-env/dev/env/ios/main.cljs and src-env/dev for our source-path so /env/{platform}/main.js isn't a problem
