### ISSUE TITLE
compileWarningsToYellowBox assumes msg is a string

### ISSUE THREAD

**Issue by seantempesta** [drapanjanas/re-natal#29]
I think [figwheel-bridge.js](https://github.com/drapanjanas/re-natal/blob/master/resources/figwheel-bridge.js) has a regression:

```
function compileWarningsToYellowBox() {
    var log = window.console.log;
    var compileWarningRx = /Figwheel: Compile Warning/;
    window.console.log = function (msg) {
        if (msg.match(compileWarningRx) != null) {
            console.warn(msg);
        } else {
            log.call(window.console, msg);
        }
    };
}
```

This function assumes that msg is a string (it can also be a javascript/cljs object) and silently fails when match is called and it's not a string.  Below is a fix.   Also, I recommend just matching on "Figwheel Compile" as there are also "Figwheel Compile Exception"s.  

```
function compileWarningsToYellowBox() {
    var log = window.console.log;
    var compileWarningRx = /Figwheel: Compile/;
    window.console.log = function (msg) {
        if (typeof msg.match === 'function' && msg.match(compileWarningRx) != null) {
            console.warn(msg);
        } else {
            log.call(window.console, msg);
        }
    };
}
```

So, I tried forking your repo and doing a pull request, but the forked repo was "natal".  Now I'm certainly no github genius, but I think this is problematic.

Also, great work on the rewrite!  Firebase is working out of the box now. :)

**Comment by drapanjanas** [comment]
True! Thanks, I will fix it as you proposed.
