### ISSUE TITLE
figwheel-bridge.js only logs first argument to log

### ISSUE THREAD

**Issue by petterik** [drapanjanas/re-natal#31]
Did:
- Called apply js/console.log with many arguments.

Expected:
- To see all arguments logged in my console.

Happened:
- Saw only the first argument being logged.

Suggested solution:
Call log with apply with all arguments:
```js
// figwheel-bridge.js

    window.console.log = function (msg) {
        if (compileWarningRx.test(msg)) {
            console.warn(msg);
        } else {
            log.apply(window.console, arguments);
        }
    };
```
Currently version:
```js
// figwheel-bridge.js

    window.console.log = function (msg) {
        if (compileWarningRx.test(msg)) {
            console.warn(msg);
        } else {
            log.call(window.console, msg);
        }
    };
```

**Comment by seantempesta** [comment]
Ah, thanks for mentioning this!  I thought I had a bug in my code. :)

**Comment by drapanjanas** [comment]
Thanks! I'll wait a bit with releasing this one, maybe some other small bugfixes pops up. Will release during weekend.
