### ISSUE TITLE
Configurable path to ios and android main.cljs

### ISSUE THREAD

**Issue by petterik** [drapanjanas/re-natal#34]
### Problem
The path to android and ios main.cljs is currently hardcoded to `env/{dev|prod}/env/{ios|android}/main.cljs`
The command `re-natal use-figwheel` cannot be configured to match my project structure (see My use case).

### Suggestion
It would be nice to have the path to `{dev|prod}/env/{ios|android}/main.cljs` configurable, i.e. having dir `env` configurable. To put something in `.re-natal` like:
```javascript
{
...
  "envRoot": "env",
...
}
```

### My use case 
I have a lot of platforms and mains - server, web and mobile - and I'd like to have the same structure for all my mains. Here's part of my current structure:
```
env/client/dev/web/main.cljs
env/client/prod/web/main.cljs
env/client/dev/ios/main.cljs
env/client/prod/ios/main.cljs
env/client/dev/android/main.cljs
...
env/common/dev/utils.cljc
...
env/server/dev/server/main.clj
env/server/dev/server/repl.clj
...
```
In my case, I'd configure `.re-natal:` `"envRoot": "env/client"`

**Comment by drapanjanas** [comment]
I think it makes sense to have such configuration possible.
Currently hardcoded path is like this `env/dev/env/ios/main.cljs`. 
So it would become `#{envRoot}/dev/env/ios/main.cljs`. In your use case the paths would be a bit different that you currently have:
```
env/client/env/prod/ios/main.cljs
env/client/env/dev/android/main.cljs
```
It would still work for you I guess.  
Feel free to submit PR if you have it working alreadt. I also can do it myslef some time.

**Comment by petterik** [comment]
Yes, exactly.

I don't have it working. I tried to create a PR real quick, but I got stuck when I had to create dirs recursively. Never having done node or coffeescript programming, I googled for while and ended up reading reading a mkdir-p lib, then called it quits ✌️

**Comment by drapanjanas** [comment]
No problem, I'll also give it a shot.

**Comment by drapanjanas** [comment]
Done, will be part of next release.
