### ISSUE TITLE
Example of creating a component?

### ISSUE THREAD

**Issue by seanhess** [drapanjanas/re-natal#38]
Hi, I'm trying to get started with re-natal. I have the sample project running, and I'm about to make my first component / sub-view. The generated project doesn't have an example sub-component, and when I try to make one according to the reagent docs, it fails. 

If I try to move the press-me button into a component:

```
(defn press-me-label [name]
  [text {:style {:color "white" :text-align "center" :font-weight "bold"}} (str "press me: " name)])
```

Then I can call it as a function as follows:

```
       ...
       [touchable-highlight {:style {:background-color "#999" :padding 10 :border-radius 5}
                             :on-press #(alert "HELLO!")}
        (press-me-label "bob")]])))
```

But the [reagent docs](https://github.com/reagent-project/reagent) specifically say you're supposed to call it as a vector:

```
       ...
       [touchable-highlight {:style {:background-color "#999" :padding 10 :border-radius 5}
                             :on-press #(alert "HELLO!")}
        [press-me-label "bob"]]])))
```

However, when I do that I get the following error:

![error](http://i.imgur.com/CorONje.png)

Am I doing something wrong? If creating components differs from reagent, can you specify in the documentation how to do so? I've trying using a Form-2 component and it still doesn't work. Am I supposed to use the function syntax? why? What if I need a component that requires setup?

**Comment by seanhess** [comment]
That isn't the right error. See here for more information: https://github.com/reagent-project/reagent/issues/232

I'll leave this open to continue to suggest that the template show at least a single example of forwarding rendering to a sub-component.

**Comment by drapanjanas** [comment]
As you already discovered it seems like this is something specific to some components like TouchableHighlight. The easy workaround is to wrap your component in View.
In other cases custom components work as expected for example:
```clojure
(defn my-text [greeting]
  [text {:style {:font-size 30 :font-weight "100" :margin-bottom 20 :text-align "center"}} greeting])

(defn app-root []
  (let [greeting (subscribe [:get-greeting])]
    (fn []
      [view {:style {:flex-direction "column" :margin 40 :align-items "center"}}
       [my-text @greeting]
       [image {:source logo-img
               :style  {:width 80 :height 80 :margin-bottom 30}}]
       [touchable-highlight {:style {:background-color "#999" :padding 10 :border-radius 5}
                             :on-press #(alert "HELLO!")}
        [text {:style {:color "white" :text-align "center" :font-weight "bold"}} "press me"]]])))
```
My current understanding of this is problem very limited, but as Reagent is a wrapper around React and not React Native so I am not sure this problem is relevant to Reagent.
