### ISSUE TITLE
re-natal use-figwheel -H 10.0.2.2` changes env/dev/env/ios/main.cljs and env/dev/env/require_img.cljs ?

### ISSUE THREAD

**Issue by localredhead** [drapanjanas/re-natal#4]
First - happy new year!  Thanks for this project!

My apologies if the answer is obvious.  We have a project where we plan to have iOS and Android code co-exist in the same repository instead of have a single repo for each.

How should we approach having a unified codebase if the host is changed for iOS and shared code when `use-figwheel -H` is used when configuring it for android?

**Comment by drapanjanas** [comment]
Hey, thanks for reporting this problem. Well, simultaneous development (when you run both apps and develop them at once) of iOS and Android is not possible at the moment. Currently, the development workflow might be something like this:
1. Start developing a feature for iOS first with `re-natal use-figwheel`
2. When feature is implemented for iOS, switch host for Android: `re-natal use-figwheel -H 10.0.2.2`
3. When feature is finished run: `lein prod-build` and test on both platforms without figwheel.
4. Commit and push new feature
You can add env/dev, index.android.js and index.ios.js to .gitignore, as these files are regenerated
Steps 1. and 2. probably could go in parallel by separate devs.

The simultneous development would be a great improvement. I will think how this can be done and will release updates. Contributions are always welcome.

You might also have a look at recent work of Artem Yarulin which looks really impressive: 
* https://github.com/artemyarulin/ktoa
* https://github.com/artemyarulin/om-next-cross-platform-template

**Comment by localredhead** [comment]
Thank you for the response and the advice.  That clears it up.

I'm more than happy to contribute back.  If I can figure out how to accomplish this I'll definitely share!

I have put some thought into it, but I'm also very new to clojure/clojurescript. At a high level I think if I set the host for android and left the host as "default" for iOS, and then had the `require_img.cljs` also split into ios/android directories when `use-figwheel` is run.  I'm very naive, for what it's worth.
