### ISSUE TITLE
Slow Rendering + Glitches on iOS 9.1

### ISSUE THREAD

**Issue by webmonarch** [drapanjanas/re-natal#42]
I just got back to working on #37 and started noticing some weird rendering issues and glitches. Specifically:

* rendering refreshes very slowly, and
* the alert OK button isn't clickable

I was able to localize it to the iOS 9.1 simulator on my machine. 8.1 works no problem. I've not tried a physical device.

I've include a screen capture of what I am seeing.  Am I the only one?  I doubt it's re-natal specific. Thanks for the sanity check.

![screen recording 2016-04-25 at 10 03 pm](https://cloud.githubusercontent.com/assets/471903/14807517/169ab632-0b32-11e6-8260-9717af19a393.gif)

**Comment by drapanjanas** [comment]
@webmonarch pls check if you have accidently enabled Debug->Slow Animations on simulator. This might be causing this.

**Comment by webmonarch** [comment]
@drapanjanas yup! you're right. It seems that `slow animation` debugging is set on all of the 9.1 simulators on my machine.  Either I was flailing pressing `CMD+T` everywhere...or it's pinned to the OS versions...or who knows what.  Thanks.
