### ISSUE TITLE
lein figwheel android hands for ever

### ISSUE THREAD

**Issue by wqhhust** [drapanjanas/re-natal#43]
I could run the following command successfully, but "lein figwheel android" runs forever, the last message is "Prompt will show when Figwheel connects to your application". What's wrong?

oracle@SomeHost /data/node-v4.4.3/bin/future-app $  re-natal use-android-device avd
Using host '10.0.2.2' for android device type 'avd'

oracle@SomeHost /data/node-v4.4.3/bin/future-app $  re-natal use-figwheel
Cleaning...
index.ios.js was regenerated
index.android.js was regenerated
AppDelegate.m was updated
Dev server host for iOS: localhost
Dev server host for Android: 10.0.2.2

oracle@SomeHost /data/node-v4.4.3/bin/future-app $ adb devices
List of devices attached 
R32D100AT3K	device

oracle@SomeHost /data/node-v4.4.3/bin/future-app $ lein figwheel android
Figwheel: Starting server at http://localhost:3449
Port 3449 is already being used. Are you running another Figwheel instance? If you want to run two Figwheel instances add a new :server-port (i.e. :server-port 3450) to Figwheel's config options in your project.clj
Figwheel: Watching build - android
Compiling "target/android/not-used.js" from ["src" "env/dev"]...
Successfully compiled "target/android/not-used.js" in 2.637 seconds.
Launching ClojureScript REPL for build: android
Figwheel Controls:
          (stop-autobuild)                ;; stops Figwheel autobuilder
          (start-autobuild [id ...])      ;; starts autobuilder focused on optional ids
          (switch-to-build id ...)        ;; switches autobuilder to different build
          (reset-autobuild)               ;; stops, cleans, and starts autobuilder
          (reload-config)                 ;; reloads build config and resets autobuild
          (build-once [id ...])           ;; builds source one time
          (clean-builds [id ..])          ;; deletes compiled cljs target files
          (print-config [id ...])         ;; prints out build configurations
          (fig-status)                    ;; displays current state of system
  Switch REPL build focus:
          :cljs/quit                      ;; allows you to switch REPL to another build
    Docs: (doc function-name-here)
    Exit: Control+C or :cljs/quit
 Results: Stored in vars *1, *2, *3, *e holds last exception object
Prompt will show when Figwheel connects to your application

**Comment by wqhhust** [comment]
if work on a emulator, it works. So as a workaround, I will work on emulator now.

**Comment by drapanjanas** [comment]
For developing using physical android device you please check this chapter in [README](https://github.com/drapanjanas/re-natal#using-real-android-device) 
Basically you need to setup the server host IP to localhost and activate forwarding of ports 8081 and 3449
```
$ re-natal use-android-device real
$ re-natal use-figwheel
$ adb reverse tcp:8081 tcp:8081
$ adb reverse tcp:3449 tcp:3449
```
