### ISSUE TITLE
how to disable fig-wheel

### ISSUE THREAD

**Issue by hanwencheng** [drapanjanas/re-natal#55]
Hi, thanks for the great framework,

I read all the document and start to use it with figwheel, but there is some problem and now I want to have a try with the original hot-Reloading Module. But after use `re-natal use-figwheel`, how to disable it to the init state? It will be nice if you can include this in the README.

**Comment by drapanjanas** [comment]
Hi, `lein prod-build` will rebuild index.*.js files with :optimizations :simple. Same is done during `re-natal init`
