### ISSUE TITLE
How do I restart react native packager?

### ISSUE THREAD

**Issue by marco-fiset** [drapanjanas/re-natal#56]
The README keeps telling us that we might need to restart the packager for the REPL to connect. How do we do that? It would be cool to include that in the README as well.

My REPL won't connect to my app, and I want to try this step but don't know how to proceed.

**Comment by drapanjanas** [comment]
To restart packager you first kill it (like close the terminal window) and start it manually:
```
$ react-native start
```
or 
```
$ npm start
```
The latter will start it without directory scanning for changes, which is done by figwheel for cljs sources.
Yes, I will add a note to README about it. Though it is expected that re-natal user has basic understanding of react-native. Re-natal does not replace any of the tools of react-native, it just adds what is relevant for development in cljs with figwheel.

**Comment by marco-fiset** [comment]
Thank you! I somehow missed something and now it works.

**Comment by swiftTr** [comment]
when creating a new react-native project and running npm install or yarn start it will give you some options in your terminal such as press q to show the QR code or press a to run on an android emulator so the key you need to press is R to restart react-native packager

**Comment by apprentice41** [comment]
@drapanjanas  Thank you!
