### ISSUE TITLE
Packager problem: "transforming index.android.js took longer than 301 seconds."

### ISSUE THREAD

**Issue by drapanjanas** [drapanjanas/re-natal#59]
I hit this problem when running app after `lein prod-build` 
A workaround for this problem can be found here: https://github.com/facebook/react-native/issues/8475

Until permanent fix, you have to downgrade to babylon@6.8.1

**Comment by tiensonqin** [comment]
I hit this too, downgrade works.

**Comment by drapanjanas** [comment]
Looks like now this is resolved with next babylon version

**Comment by rasom** [comment]
This error can appear again because of `babel-plugin-transform-es2015-block-scoping@6.18.0`. You can fix this by downgrading it to `babel-plugin-transform-es2015-block-scoping@6.15.0`

https://github.com/babel/babel/issues/4795

**Comment by Mamun** [comment]
Hi Rasom,
What do I need to do downgrading plugin? 
Which file do I need to change and do I need to run any command to downgrade it?

Mamun

**Comment by rasom** [comment]
@Mamun , you can specify package version in `package.json`
```
 "babel-plugin-transform-es2015-block-scoping": "6.15.0"
```
remove `node_modules` directory and then run `npm install`.
