### ISSUE TITLE
Talk about React Native on Clojure/West 2016

### ISSUE THREAD

**Issue by artemyarulin** [drapanjanas/re-natal#6]
Hi,

This is an awesome tool that you have here and currently on the list of [suggested topics](https://github.com/clojurewest/clojurewest2016/wiki/Suggested-Topics) to the Clojure/West conference ClojureScript + ReactNative is wining, people are interested in this.

We should spread the news about ClojureScript and React Native. Currently there are not that much videos exists about this topics and I'm almost sure that many folks from JS community would be crazy to see REPL support (unique feature for ClojureScript) and macroses I'm sure would blow their mind! :)

**Comment by drapanjanas** [comment]
Hey, thanks, I also like the tool! Dan Motzenbecker and Will Decker gets most of the credits ;)
I think its a really good idea to do the talk and overview all the latest tools. I vote for Mike Fikes :) He maintains http://cljsrn.org and did a number of great blogposts, so in my opinion he would be best guy for the topic.

**Comment by arichiardi** [comment]
I vote for this as well, it basically is the (open source) answer to JRebel but cross-platform. We should really push it. I was considering giving a talk, but @mfikes for sure has more experience in both React Native and being exposed to cameras :smile:

**Comment by mfikes** [comment]
Thanks for the votes :) I'd like to actually build some stuff with ClojureScript and React Native, which could lead to some substance to talk about. I actually don't have all that much experience with it yet. :/

I suspect the first CLJS + RN apps will start shipping soon. I wish I had built one by now. :)

**Comment by artemyarulin** [comment]
> `I'm too afraid of such responsibility, and I am lazy, and and and ` :smile:

closing then :smile:
