### ISSUE TITLE
Switch schema out for cljs.spec

### ISSUE THREAD

**Issue by cldwalker** [drapanjanas/re-natal#60]
Would you be interested in a PR to change schema in [cljs-reagent6](https://github.com/drapanjanas/re-natal/tree/master/resources/cljs-reagent6) for cljs.spec? This will require upgrading the template to use latest clojurescript and a clojure 1.8.0-alpha version. I've been using cljs.spec in deployed ios + android re-natal apps and it's been working great :)

**Comment by drapanjanas** [comment]
Hey, thanks, that sounds great. I was also thinking about doing this when have some time. Why clojure 1.8.0-alpha? I guess you meant 1.9.0-alpha.

**Comment by cldwalker** [comment]
Cool. Yep I meant 1.9. I'm traveling now but hope to get to this in a week or two
