### ISSUE TITLE
Error with fresh install / run

### ISSUE THREAD

**Issue by dfcarpenter** [drapanjanas/re-natal#61]
Tried reinstalling and following all install / run steps correctly.

![image](https://cloud.githubusercontent.com/assets/4450286/16967501/16940b60-4dbe-11e6-8c25-fefdd4984a44.png)

**Comment by drapanjanas** [comment]
Hmm, don't recall hitting this one. Could you please provide the versions of RN, re-natal? 
Is this error thrown only when you run with figwheel or also without it (`lein prod-build`)?
