### ISSUE TITLE
Stop working during initialize new project

### ISSUE THREAD

**Issue by yottanami** [drapanjanas/re-natal#66]
I am trying to initialize new project but it stops during `Creating React Native skeleton.`
I wait about one hour but it did not work.
I also tried using http_proxy

Is there anyway see the what is happening behind?
As I checked  there is a --verbose option in natal but not in re-natal

**Comment by drapanjanas** [comment]
Hey, what you could do is `cd` into a folder which was created during aborted `re-natal init` command and run `npm i`. That is usally takes most of the time.
I have moved some things around after fork so new things in natal were not mergeable, --verbose optin is useful I agree we should have that in re-natal too.

**Comment by j-h-l** [comment]
Are you (@yottanami) by any chance on mac sierra?  This is happening to me after the upgrade. (re-natal version 0.2.43)

**Comment by j-h-l** [comment]
Looked in generated `package.json` it looks like `"react": "15.3.1"` or something like it is missing

**Comment by j-h-l** [comment]
I was able to fix this problem by following this:

> I also ran into this issue and can confirm that the problem is watchman. I had used homebrew to uninstall/reinstall and was still running into the same issues. My steps to solve were the following:

> Uninstall watchman with homebrew
> Delete the contents of the /usr/local/var/run/watchman/ folder
> Re-install watchman with homebrew
> I was able to figure out the extra step of deleting the contents of the watchman folder from these two github issues: - https://github.com/facebook/watchman/issues/361 - https://github.com/facebook/watchman/issues/358#issuecomment-246672605

[React Native hanging Forever stackoverflow answer](http://stackoverflow.com/questions/39546151/react-native-hangs-forever/39631840)
