### ISSUE TITLE
Cannot connect to figwheel

### ISSUE THREAD

**Issue by MaksymDev** [drapanjanas/re-natal#67]
"adb reverse" - is not available for android version prior to 5.0. So, I cannot use to reverse-forward port 3449 from android localhost to my Dev machine.
Need a way to specify IP to use by figwheel

**Comment by drapanjanas** [comment]
To workaround this, I think you can set your IP address of your local figwheel server in the .re-natal config file manually:
```
"androidHost": "your.local.ip.addr",
```
Run re-natal use-figwheel and try if it works.

If it works fine, I can update the command `re-natal use-android-device` to accept IP address similar how it is done in `re-natal use-ios-device`
