### ISSUE TITLE
Update README dependencies

### ISSUE THREAD

**Issue by jiangts** [drapanjanas/re-natal#7]
I tried creating a new project with `re-natal 0.2.13` and was unable to start the app due to an "importScript not defined" error.

It was fixed by upgrading `react-native-cli` to the latest version, `1.9`. Please add this as a dependency in the README to save other people time! :)

**Comment by drapanjanas** [comment]
Thank your for reporting this. I have `react-native-cli` version 0.1.7 and all seem to work fine, so I left 0.1.7 as a minimum version. Just for dull information, could you please better describe how did you get this error? Did the error occur in xcode for iOS? or during Android build? Thank you.

**Comment by jiangts** [comment]
It was an error message on the iOS simulator actually. I think `importScript` was in `figwheel-bridge.js` and was not found in the js context.
