### ISSUE TITLE
Show CLJS compilation errors and other warnings on screen

### ISSUE THREAD

**Issue by drapanjanas** [drapanjanas/re-natal#8]
Currently, when using figwheel CLJS compilation erros are almost invisible. Same as other errors like if you mistyped some property name: instead of `:font-weight` you accidently typed `:font-weihgt` such error stays not visible.
If you use React Native without CLJS and figwheel you would see warnings in yellow box at the bottom of simulator screen.

**Comment by drapanjanas** [comment]
<img width="487" alt="screen shot 2016-01-10 at 20 20 21" src="https://cloud.githubusercontent.com/assets/1648448/12223439/d45aeac4-b7d7-11e5-9346-b9e8745a7047.png">

**Comment by arichiardi** [comment]
:+1: Nice
