### ISSUE TITLE
figwheel-bridge.js requires `"figwheel.connect." + platform` when it spits out just "figwheel.connect"

### ISSUE THREAD

**Issue by levitanong** [drapanjanas/re-natal#80]
The error is `"goog.require could not find: figwheel.connect.ios"`.

As the title says, there is a mismatch between the output file and what figwheel-bridge is looking for.

**Comment by drapanjanas** [comment]
Hi, I think figwheel.connect.${platform} was needed to work with figwheel version 0.5.8. Try setting lein-figwheel and figwheel-sidecar versions to 0.5.8 in your project.clj

**Comment by levitanong** [comment]
Forgot to close this. I can't remember whether or not this worked, but I'm not encountering this problem right now. :P
