### ISSUE TITLE
Automatic (push) reloads not working anymore.

### ISSUE THREAD

**Issue by carlhu** [drapanjanas/re-natal#89]
Things have been going smoothly for a while, but recently, automatic reloads (without hitting ctrl-R in the emulator on ios) stopped working. 

In the de bugger, a printout shows this (but nothing else informative). 
```
2016-12-29 14:25:15.334 [info][tid:com.facebook.react.JavaScript] Figwheel: Compile Exception
2016-12-29 14:25:15.335 [info][tid:com.facebook.react.JavaScript]  : 
2016-12-29 14:26:35.894798 [84303:5738092] [] __nw_connection_get_connected_socket_block_invoke 121 Connection has no connected handler
```

Fortunately, ctrl-r works. 

As well, `build-clean` works  and shows  no errors.

A couple of hypotheses:
1. I recently upgraded xcode to 8.2.1
2. The project of course is steadily growing in size, but it's really not that big?

Note that I've previously upped the memory for node as specified in another bug, and it resolved OOM issues I experienced. 

Any thoughts?

**Comment by drapanjanas** [comment]
I would try figuring out how does this line occur:
```
2016-12-29 14:25:15.334 [info][tid:com.facebook.react.JavaScript] Figwheel: Compile Exception
```
This looks like figwheel can't complie the cljs code, though I would expect that clean build would show the error. But seems that is not the case.

**Comment by carlhu** [comment]
Thank you, Artur. I started a new project and copied all the code over (one
fcn at at time) and now it works. All good now.

**Comment by carlhu** [comment]
Confirmed.
