### ISSUE TITLE
example app

### ISSUE THREAD

**Issue by pishty1** [drapanjanas/re-natal#92]
Hello guys, 

Just wondering if you have an example app with firebase storage and social authentication ?

regards

**Comment by carocad** [comment]
@pishty1 you can find an example and guidance here: https://firebase.googleblog.com/2016/01/the-beginners-guide-to-react-native-and_84.html. I havent seen anything on CLJS though but it shouldnt be much of a problem I guess.

**Comment by pishty1** [comment]
thanks man, will have a look
