### ISSUE TITLE
Upgrade to react native 0.41

### ISSUE THREAD

**Issue by dupuchba** [drapanjanas/re-natal#96]
Can we upgrade react-native version to 0.41 here ? 
https://github.com/drapanjanas/re-natal/blob/b8b60dd2e285d48776009d908f38a4ee4f0cfac5/re-natal.coffee#L33

**Comment by drapanjanas** [comment]
Sure, thanks! Will publish soon.

**Comment by dupuchba** [comment]
is there anything to do other than upgrading the version ?

**Comment by dupuchba** [comment]
ok, did not see this one https://github.com/drapanjanas/re-natal/pull/94
thanks !
